version: '3.8'

services:
  recipe-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: recipe-app
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 